### ISSUE TITLE
Pipeline edge/SimulatedEdgeDevice/build.yaml is incorrect

### ISSUE THREAD

**Issue by lokijota** [Azure-Samples/iot-edge-watchdog#13]
Please provide a succinct description of the issue.

This file has this at the top:

`azureContainerRegistry: contoso.azurecr.io`

and then in the step:

`azureContainerRegistry: $(azureContainerRegistry) # as '{"loginServer": "{target}.azurecr.io"}'`

This generates an error like:

` ##[error]SyntaxError: Unexpected token v in JSON at position 0`

In my case, my ACR starts with character `v`.

This should have this syntax:

`{"loginServer":"ACRNAME.azurecr.io", "id" : "/subscriptions/SUBSCRIPTION-GUID/resourceGroups/RESOURCE-GROUP-NAME/providers/Microsoft.ContainerRegistry/registries/ACRNAME"}'`

Provide the steps required to reproduce the problem:

Just try to run the pipeline in Azure Devops.

**Comment by WilliamBerryiii** [comment]
@kln4dt - should we update this to use the latest build tasks?

**Comment by WilliamBerryiii** [comment]
Build Yaml updated.
