### ISSUE TITLE
Replace Zip file in sample

### ISSUE THREAD

**Issue by lokijota** [Azure-Samples/iot-edge-watchdog#14]
Considering the 1st result when searching for the IoT Edge watchdog is <https://docs.microsoft.com/en-us/samples/azure-samples/iot-edge-watchdog/azure-iot-edge-watchdog/<, and that teh ZIP file included there is full of issues (errors in dockerfile, module.json, build.yaml, etc.), I strongly recommend that either the ZIP from that page is completely removed or **bold text** is added at the top telling people to use the github version. It would have spared me hours of frustration.

Also note there's no way to comment on that page.

**Comment by WilliamBerryiii** [comment]
@lokijota - thanks. We'll investigate why the zip of the repository is out of date. That archive is autogenerated by the Azure-Samples org ... we'll ping them to see what's up.

**Comment by WilliamBerryiii** [comment]
This will be fixed with the following PR into MSFT Docs Sample repo - once those checks clear. https://github.com/MicrosoftDocs/samples/pull/1557

**Comment by WilliamBerryiii** [comment]
This was fixed in MicrosoftDocs/samples#1558 and should be live soon.
