### ISSUE TITLE
edge/SimulatedEdgeDevice/deployment.template.json is wrong

### ISSUE THREAD

**Issue by lokijota** [Azure-Samples/iot-edge-watchdog#15]
The above file mentions `BEAT_FREQUENCY_IN_SECONDS` in the env section. It should be `HEARTBEAT_FREQUENCY_IN_SECONDS`. 

At times this sample felt like a coding exercise in finding bugs.

**Comment by lokijota** [comment]
Additionally, I believe `DEVICE_NAME` in the above file is also not used. It's not present in the `.env` file nor in the visual studio solution.

**Comment by WilliamBerryiii** [comment]
@lokijota - thanks for filing the issue. This has been fixed.
