### ISSUE TITLE
Watchdog Dockerfile.amd64 does not build, references non-existent folder and project names

### ISSUE THREAD

**Issue by judyer28** [Azure-Samples/iot-edge-watchdog#6]
Please provide a succinct description of the issue.
The edge/SimulatedEdgeDevice/modules/Watchdog/Dockerfile.amd64 does not build as it references non-existent folder and project names.  For example, the command "COPY EdgeHeartbeatMessage/EdgeHeartbeatMessage.csproj /app/EdgeHeartbeatMessage/" will not work as those folders and project names do not exist.

**Repro steps**
Provide the steps required to reproduce the problem:

1. In VS Code, right click on edge\SimulatedEdgeDevice\deployment.template.json and select Build IoT Edge Solution.  The build will fail on attempt to perform COPY command mentioned above.  

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

Provide a description of the expected behavior.
Should successfully build module image using Dockerfile

**Actual behavior**
Fails due to multiple issues beginning with refences to non-existent directories and csproj files.

Provide a description of the actual behaviour observed. 

**Known workarounds**

Provide a description of any known workarounds.

**Related information**

Provide any related information (optional):

* Operating system
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
* Editing Tools (e.g. Visual Studio Version, Visual Studio)
Visual Studio Code with Azure IoT Edge extension

**Comment by WilliamBerryiii** [comment]
Should be closed via commit #7 - please let us know if there are further issues (cc/ @kln4dt )
